//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_ZCGL
    {
        public int ComId { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string EPCode { get; set; }
        public string FactoryCode { get; set; }
        public string Tag { get; set; }
        public int BranchCode { get; set; }
        public string UserGW { get; set; }
        public string UserName { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Location { get; set; }
        public int Status { get; set; }
        public int TypeID { get; set; }
        public string Comment { get; set; }
        public double OrginalPrice { get; set; }
        public double PresentPrice { get; set; }
        public int Qty { get; set; }
        public System.DateTime RegistDate { get; set; }
        public int Depreciation { get; set; }
        public string CRUser { get; set; }
        public System.DateTime CRDate { get; set; }
        public int IsDel { get; set; }
        public string Managezhiwu { get; set; }
        public string Desc { get; set; }
        public string Situation { get; set; }
        public string Verify { get; set; }
        public Nullable<int> IndexID { get; set; }
    }
}
