//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_HYGL_OUTUSER
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> HYGLID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> OutDept { get; set; }
        public string Zhiwu { get; set; }
        public string Mobphone { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string RoomNumber { get; set; }
        public string BoardingTime { get; set; }
        public string CarNumber { get; set; }
        public string YCTIME { get; set; }
        public string YCLOCATION { get; set; }
        public Nullable<int> ServiceUser { get; set; }
        public string Comment { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> PickupType { get; set; }
        public string PickupNumber { get; set; }
        public string PickupDate { get; set; }
        public Nullable<int> SendoffType { get; set; }
        public string SendoffNumber { get; set; }
        public string SendoffDate { get; set; }
        public string PickupUser { get; set; }
        public string PickupUserMob { get; set; }
        public string PickupCarNumber { get; set; }
        public string PickupLocation { get; set; }
        public string SendoffUser { get; set; }
        public string SendoffUserMob { get; set; }
        public string SendoffCarNumber { get; set; }
        public string SendoffLocation { get; set; }
        public string HotelName { get; set; }
        public string HotelRegion { get; set; }
        public string HotelLocation { get; set; }
    }
}
