//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_ZCGL_LifeCycle
    {
        public int ComId { get; set; }
        public int ID { get; set; }
        public int ZCGLID { get; set; }
        public string Title { get; set; }
        public int TypeID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string FromUser { get; set; }
        public string ToUser { get; set; }
        public string Comment { get; set; }
        public string CRUser { get; set; }
        public System.DateTime CRDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int IsDel { get; set; }
    }
}
