//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WX_UserGroup
    {
        public Nullable<int> ComId { get; set; }
        public string UserName { get; set; }
        public int GroupCode { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string InvitationUser { get; set; }
    }
}
