//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WX_User
    {
        public int ID { get; set; }
        public string Openid { get; set; }
        public string Nickname { get; set; }
        public string Sex { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string HeadImgUrl { get; set; }
        public string Privilege { get; set; }
        public string Unionid { get; set; }
        public string Access_token { get; set; }
        public Nullable<int> Expires_in { get; set; }
        public string Refresh_token { get; set; }
        public string Scope { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public int AuthUserID { get; set; }
        public string Code { get; set; }
    }
}
